/**
 * Copyright @ 2014 - 2017 Suntec Software(Shanghai) Co., Ltd.
 * All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are NOT permitted except as agreed by
 * Suntec Software(Shanghai) Co., Ltd.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */

#include "VR_DataAccessorNaviCN.h"

#include "gtest/gtest.h"

/**
* VR_DataAccessorNaviCN_Test
*
* The class is just for VR_DataAccessorNaviCN test.
*/
class VR_DataAccessorNaviCN_Test : public testing::Test
{
public:
    VR_DataAccessorNaviCN_Test()
    {
    }

    static void SetUpTestCase() {}
    static void TearDownTestCase() {}
    virtual void SetUp() {}
    virtual void TearDown() {}

private:
    VR_DataAccessorNaviCN_Test(const VR_DataAccessorNaviCN_Test& other);
    void operator= (const VR_DataAccessorNaviCN_Test& other);
};

TEST_F(VR_DataAccessorNaviCN_Test, getInfo)
{
    VR_DataAccessorNaviCN accessorNavi;
    std::string reqMsg;
    std::string response;
    accessorNavi.getInfo("_addressMappingCN", reqMsg, response);
    accessorNavi.getInfo("_buildAddressCN", reqMsg, response);
    accessorNavi.getInfo("_buildPointType", reqMsg, response);
    accessorNavi.getInfo("otheroperation", reqMsg, response);
    SUCCEED();
}

TEST_F(VR_DataAccessorNaviCN_Test, isOperationHandled)
{
    VR_DataAccessorNaviCN accessorNavi;
    EXPECT_FALSE(accessorNavi.isOperationHandled(""));
    EXPECT_FALSE(accessorNavi.isOperationHandled("otheroperation"));
    EXPECT_TRUE(accessorNavi.isOperationHandled("_addressMappingCN"));
    EXPECT_TRUE(accessorNavi.isOperationHandled("_buildAddressCN"));
    EXPECT_TRUE(accessorNavi.isOperationHandled("_buildPointType"));
}

TEST_F(VR_DataAccessorNaviCN_Test, addressMapping)
{
    VR_DataAccessorNaviCN accessorNavi;

    std::string reqMsg;
    std::string response;
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>abc</zone>"
                                    "<city></city>"
                                    "<district></district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>cde</zone>"
                                    "<city></city>"
                                    "<district></district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>efg</zone>"
                                    "<city></city>"
                                    "<district></district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>abc</zone>"
                                    "<city>efs</city>"
                                    "<district></district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>cde</zone>"
                                    "<city>fae</city>"
                                    "<district></district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>efg</zone>"
                                    "<city>afeaw</city>"
                                    "<district></district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>abc</zone>"
                                    "<city>fase</city>"
                                    "<district>afsef</district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>cde</zone>"
                                    "<city>fesaf</city>"
                                    "<district>fasef</district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>efg</zone>"
                                    "<city>fergaw</city>"
                                    "<district>fasge</district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>abc</zone>"
                                    "<city>fase</city>"
                                    "<district>afsef</district>"
                                    "<street>wertwer</street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>cde</zone>"
                                    "<city>fesaf</city>"
                                    "<district>fasef</district>"
                                    "<street>trwerte</street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>efg</zone>"
                                    "<city>fergaw</city>"
                                    "<district>fasge</district>"
                                    "<street>uurtr</street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>abc</zone>"
                                    "<city>fase</city>"
                                    "<district>afsef</district>"
                                    "<street>wertwer</street>"
                                    "<streetBody>uouihj</streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>cde</zone>"
                                    "<city>fesaf</city>"
                                    "<district>fasef</district>"
                                    "<street>trwerte</street>"
                                    "<streetBody>kyukyu</streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>efg</zone>"
                                    "<city>fergaw</city>"
                                    "<district>fasge</district>"
                                    "<street>uurtr</street>"
                                    "<streetBody>kyuyt</streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>abc</zone>"
                                    "<city>fase</city>"
                                    "<district>afsef</district>"
                                    "<street>wertwer</street>"
                                    "<streetBody>uouihj</streetBody>"
                                    "<houseNumber>123</houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>cde</zone>"
                                    "<city>fesaf</city>"
                                    "<district>fasef</district>"
                                    "<street>trwerte</street>"
                                    "<streetBody>kyukyu</streetBody>"
                                    "<houseNumber>72</houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>efg</zone>"
                                    "<city>fergaw</city>"
                                    "<district>fasge</district>"
                                    "<street>uurtr</street>"
                                    "<streetBody>kyuyt</streetBody>"
                                    "<houseNumber>12</houseNumber>"
                                "</addressId>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>abc</zone>"
                                    "<city>fase</city>"
                                    "<district>afsef</district>"
                                    "<street>wertwer</street>"
                                    "<streetBody>uouihj</streetBody>"
                                    "<houseNumber>123</houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>cde</zone>"
                                    "<city>fesaf</city>"
                                    "<district>fasef</district>"
                                    "<street>trwerte</street>"
                                    "<streetBody>kyukyu</streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone>efg</zone>"
                                    "<city>fergaw</city>"
                                    "<district>fasge</district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<addressId>"
                                    "<zoneId></zoneId>"
                                    "<cityId></cityId>"
                                    "<districtId></districtId>"
                                    "<streetId></streetId>"
                                    "<zone></zone>"
                                    "<city></city>"
                                    "<district></district>"
                                    "<street></street>"
                                    "<streetBody></streetBody>"
                                    "<houseNumber></houseNumber>"
                                "</addressId>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    reqMsg = "<data>"
                "<index>0</index>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.addressMapping(reqMsg, response);

    SUCCEED();
}

TEST_F(VR_DataAccessorNaviCN_Test, buildAddress)
{
    VR_DataAccessorNaviCN accessorNavi;

    std::string reqMsg;
    std::string response;
    accessorNavi.buildAddress(reqMsg, response);

    reqMsg = "<data>"
                "<buildType>STATE</buildType>"
                "<addressInfo>"
                    "<zoneId></zoneId>"
                    "<cityId></cityId>"
                    "<districtId></districtId>"
                    "<streetId></streetId>"
                    "<zone>yerg</zone>"
                    "<city>shtjy</city>"
                    "<district>tuqfg</district>"
                    "<street>jsefs</street>"
                    "<streetBody>uiwvhtw</streetBody>"
                    "<houseNumber>854</houseNumber>"
                "</addressInfo>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>abc</zone>"
                                "<city>fase</city>"
                                "<district>afsef</district>"
                                "<street>wertwer</street>"
                                "<streetBody>uouihj</streetBody>"
                                "<houseNumber>123</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>cde</zone>"
                                "<city>fesaf</city>"
                                "<district>fasef</district>"
                                "<street>trwerte</street>"
                                "<streetBody>kyukyu</streetBody>"
                                "<houseNumber>72</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>efg</zone>"
                                "<city>fergaw</city>"
                                "<district>fasge</district>"
                                "<street>uurtr</street>"
                                "<streetBody>kyuyt</streetBody>"
                                "<houseNumber>12</houseNumber>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.buildAddress(reqMsg, response);

    reqMsg = "<data>"
                "<buildType>CITY</buildType>"
                "<addressInfo>"
                    "<zoneId></zoneId>"
                    "<cityId></cityId>"
                    "<districtId></districtId>"
                    "<streetId></streetId>"
                    "<zone>yerg</zone>"
                    "<city>shtjy</city>"
                    "<district>tuqfg</district>"
                    "<street>jsefs</street>"
                    "<streetBody>uiwvhtw</streetBody>"
                    "<houseNumber>854</houseNumber>"
                "</addressInfo>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>abc</zone>"
                                "<city>fase</city>"
                                "<district>afsef</district>"
                                "<street>wertwer</street>"
                                "<streetBody>uouihj</streetBody>"
                                "<houseNumber>123</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>cde</zone>"
                                "<city>fesaf</city>"
                                "<district>fasef</district>"
                                "<street>trwerte</street>"
                                "<streetBody>kyukyu</streetBody>"
                                "<houseNumber>72</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>efg</zone>"
                                "<city>fergaw</city>"
                                "<district>fasge</district>"
                                "<street>uurtr</street>"
                                "<streetBody>kyuyt</streetBody>"
                                "<houseNumber>12</houseNumber>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.buildAddress(reqMsg, response);

    reqMsg = "<data>"
                "<buildType>DISTRICT</buildType>"
                "<addressInfo>"
                    "<zoneId></zoneId>"
                    "<cityId></cityId>"
                    "<districtId></districtId>"
                    "<streetId></streetId>"
                    "<zone>yerg</zone>"
                    "<city>shtjy</city>"
                    "<district>tuqfg</district>"
                    "<street>jsefs</street>"
                    "<streetBody>uiwvhtw</streetBody>"
                    "<houseNumber>854</houseNumber>"
                "</addressInfo>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>abc</zone>"
                                "<city>fase</city>"
                                "<district>afsef</district>"
                                "<street>wertwer</street>"
                                "<streetBody>uouihj</streetBody>"
                                "<houseNumber>123</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>cde</zone>"
                                "<city>fesaf</city>"
                                "<district>fasef</district>"
                                "<street>trwerte</street>"
                                "<streetBody>kyukyu</streetBody>"
                                "<houseNumber>72</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>efg</zone>"
                                "<city>fergaw</city>"
                                "<district>fasge</district>"
                                "<street>uurtr</street>"
                                "<streetBody>kyuyt</streetBody>"
                                "<houseNumber>12</houseNumber>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.buildAddress(reqMsg, response);

    reqMsg = "<data>"
                "<buildType>STREET</buildType>"
                "<addressInfo>"
                    "<zoneId></zoneId>"
                    "<cityId></cityId>"
                    "<districtId></districtId>"
                    "<streetId></streetId>"
                    "<zone>yerg</zone>"
                    "<city>shtjy</city>"
                    "<district>tuqfg</district>"
                    "<street>jsefs</street>"
                    "<streetBody>uiwvhtw</streetBody>"
                    "<houseNumber>854</houseNumber>"
                "</addressInfo>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>abc</zone>"
                                "<city>fase</city>"
                                "<district>afsef</district>"
                                "<street>wertwer</street>"
                                "<streetBody>uouihj</streetBody>"
                                "<houseNumber>123</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>cde</zone>"
                                "<city>fesaf</city>"
                                "<district>fasef</district>"
                                "<street>trwerte</street>"
                                "<streetBody>kyukyu</streetBody>"
                                "<houseNumber>72</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>efg</zone>"
                                "<city>fergaw</city>"
                                "<district>fasge</district>"
                                "<street>uurtr</street>"
                                "<streetBody>kyuyt</streetBody>"
                                "<houseNumber>12</houseNumber>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.buildAddress(reqMsg, response);

    reqMsg = "<data>"
                "<buildType>NUMBER</buildType>"
                "<addressInfo>"
                    "<zoneId></zoneId>"
                    "<cityId></cityId>"
                    "<districtId></districtId>"
                    "<streetId></streetId>"
                    "<zone>yerg</zone>"
                    "<city>shtjy</city>"
                    "<district>tuqfg</district>"
                    "<street>jsefs</street>"
                    "<streetBody>uiwvhtw</streetBody>"
                    "<houseNumber>854</houseNumber>"
                "</addressInfo>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>abc</zone>"
                                "<city>fase</city>"
                                "<district>afsef</district>"
                                "<street>wertwer</street>"
                                "<streetBody>uouihj</streetBody>"
                                "<houseNumber>123</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>cde</zone>"
                                "<city>fesaf</city>"
                                "<district>fasef</district>"
                                "<street>trwerte</street>"
                                "<streetBody>kyukyu</streetBody>"
                                "<houseNumber>72</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>efg</zone>"
                                "<city>fergaw</city>"
                                "<district>fasge</district>"
                                "<street>uurtr</street>"
                                "<streetBody>kyuyt</streetBody>"
                                "<houseNumber>12</houseNumber>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.buildAddress(reqMsg, response);

    reqMsg = "<data>"
                "<buildType>OTHER</buildType>"
                "<addressInfo>"
                    "<zoneId></zoneId>"
                    "<cityId></cityId>"
                    "<districtId></districtId>"
                    "<streetId></streetId>"
                    "<zone>yerg</zone>"
                    "<city>shtjy</city>"
                    "<district>tuqfg</district>"
                    "<street>jsefs</street>"
                    "<streetBody>uiwvhtw</streetBody>"
                    "<houseNumber>854</houseNumber>"
                "</addressInfo>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>abc</zone>"
                                "<city>fase</city>"
                                "<district>afsef</district>"
                                "<street>wertwer</street>"
                                "<streetBody>uouihj</streetBody>"
                                "<houseNumber>123</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>cde</zone>"
                                "<city>fesaf</city>"
                                "<district>fasef</district>"
                                "<street>trwerte</street>"
                                "<streetBody>kyukyu</streetBody>"
                                "<houseNumber>72</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>efg</zone>"
                                "<city>fergaw</city>"
                                "<district>fasge</district>"
                                "<street>uurtr</street>"
                                "<streetBody>kyuyt</streetBody>"
                                "<houseNumber>12</houseNumber>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.buildAddress(reqMsg, response);

    reqMsg = "<data>"
                "<buildType>STREET</buildType>"
                "<addressInfo>"
                    "<zoneId></zoneId>"
                    "<cityId></cityId>"
                    "<districtId></districtId>"
                    "<streetId></streetId>"
                    "<zone>yerg</zone>"
                    "<city>shtjy</city>"
                    "<district>tuqfg</district>"
                    "<street>jsefs</street>"
                    "<streetBody>uiwvhtw</streetBody>"
                    "<houseNumber>854</houseNumber>"
                "</addressInfo>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>abc</zone>"
                                "<city>fase</city>"
                                "<district>afsef</district>"
                                "<street>wertwer</street>"
                                "<streetBody>uouihj</streetBody>"
                                "<houseNumber>123</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>cde</zone>"
                                "<city>fesaf</city>"
                                "<district>fasef</district>"
                                "<street>trwerte</street>"
                                "<houseNumber>72</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>efg</zone>"
                                "<city>fergaw</city>"
                                "<district>fasge</district>"
                                "<street>uurtr</street>"
                                "<streetBody>kyuyt</streetBody>"
                                "<houseNumber>12</houseNumber>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.buildAddress(reqMsg, response);

    reqMsg = "<data>"
                "<buildType>STREET</buildType>"
                "<addressInfo>"
                    "<zoneId></zoneId>"
                    "<cityId></cityId>"
                    "<districtId></districtId>"
                    "<streetId></streetId>"
                    "<zone>yerg</zone>"
                    "<city>shtjy</city>"
                    "<district>tuqfg</district>"
                    "<street>jsefs</street>"
                    "<streetBody>uiwvhtw</streetBody>"
                    "<houseNumber>854</houseNumber>"
                "</addressInfo>"
                "<asrResult>"
                    "<list id=\"asr1\">"
                        "<header>"
                            "<pageSize>0</pageSize>"
                            "<startIndex>0</startIndex>"
                            "<count>3</count>"
                        "</header>"
                        "<items>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>abc</zone>"
                                "<city>fase</city>"
                                "<district>afsef</district>"
                                "<street>wertwer</street>"
                                "<streetBody>uouihj</streetBody>"
                                "<houseNumber>123</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>cde</zone>"
                                "<city>fesaf</city>"
                                "<district>fasef</district>"
                                "<street>trwerte</street>"
                                "<streetBody></streetBody>"
                                "<houseNumber>72</houseNumber>"
                            "</item>"
                            "<item>"
                                "<zoneId></zoneId>"
                                "<cityId></cityId>"
                                "<districtId></districtId>"
                                "<streetId></streetId>"
                                "<zone>efg</zone>"
                                "<city>fergaw</city>"
                                "<district>fasge</district>"
                                "<street>uurtr</street>"
                                "<streetBody>kyuyt</streetBody>"
                                "<houseNumber>12</houseNumber>"
                            "</item>"
                        "</items>"
                    "</list>"
                "</asrResult>"
            "</data>";
    accessorNavi.buildAddress(reqMsg, response);

    SUCCEED();
}

/* EOF */